name: Try to run the example of nomad in matlab

on:
  # Trigger the workflow on push or pull request
  push:
  # Trigger the workflow manually
  schedule:
    - cron: '0 22 */7 * *'
  workflow_dispatch:

env:
    GFORTRAN_VERSION: 12

jobs:
  test:
    name: Tough test.
    runs-on: ${{matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone NOMAD
        uses: actions/checkout@v3
        with:
          repository: bbopt/nomad
          path: nomad

      - name: Install cmake
        run: sudo apt-get update && sudo apt-get install cmake

      - name: Configuration
        run: cd ./nomad && cmake -DTEST_OPENMP=OFF -DBUILD_INTERFACE_MATLAB=ON -DBUILD_INTERFACE_PYTHON=ON -S . -B build/release

      - name: Build
        run: cmake --build build/release

      - name: Install
        run: cmake --install build/release       

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3.3.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v1.2.0
        with:
          command:
            cd(./interfaces/Matlab_MEX);
            test_nomad_gerad

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test_bds_small
          path: ./tests/testdata
